[package]
name = "video"
version = "0.1.0"
edition = "2024"
authors = ["boris.lok.tw@outlook.com"]

[[bin]]
path = "src/bin/video.rs"
name = "video"

[lib]
path = "src/lib.rs"

[dependencies]
clap = { version = "4.5.47", features = ["cargo"] }
